Revert "Locale fixes for when there are no xlocale extesions"
This reverts commit 8f2d7c0880361abbcf4ccaca0a9d4e2dda6f1a63.

Breaks building with clang:
/tmp/ndk-libcxx-clang++/ndk/sources/cxx-stl/llvm-libc++/libcxx/src/locale.cpp:46:12:
error: static declaration of 'islower_l' follows non-static declaration
static int islower_l(int __ch, locale_t __l) {
           ^
/Users/thakis/src/insanity/ndk/sources/android/support/include/ctype.h:45:5:
note: previous declaration is here
int islower_l(int, locale_t);
    ^